### PR TITLE
Properly use krb5_enctype in vectors

### PR DESCRIPTION
**Pull request by michael-o**
This compiles for me on:
* FreeBSD: Clang, GCC with Heimdal, MIT Kerberos
* HP-UX: aCC and MIT Kerberos

### CODE REVIEW

**Comment by oflebbe** [comment]
honestly, I don't like these many casts.

**Comment by michael-o** [comment]
I understand,  but the reason is Heimdal's enum. Maybe just int32?

**Comment by oflebbe** [comment]
int32 seems much more unproblematic .

**Comment by michael-o** [comment]
@oflebbe Done, trivial change now.

**Pull request closed without merging**
