### PR TITLE
Pull latest fixes from master into v1_1 release branch

### PR DESCRIPTION
**Pull request by dkobras**
Latest cleanups to `master` branch affect `v1_1` as well, and should get merged before the final release.

### CODE REVIEW

**Comment by oflebbe** [comment]
This was the plan. I wanted to develop these fixes on master and merge them into release v1_1.

**Comment by michael-o** [comment]
Can we name the branch for the stupid simply: 1.1.x? I never understood why people replace dots with underscopes.

**Comment by oflebbe** [comment]
we should keep a consistent naming, regardless: v1_0 was there before.

**Comment by michael-o** [comment]
But this implies that this is a tag with the version 1.0 and not a maintanence branch für 1.0.x.

**Comment by oflebbe** [comment]
Hm ... do I really should push something on dkobras/msktutil ?

bildschirmfoto 2018-06-25 um 20 54 32

**Pull request merged**
