### PR TITLE
fix: Remove unused function get_host_os

### PR DESCRIPTION
**Pull request by oflebbe**
Unused function

### CODE REVIEW

**Comment by michael-o** [comment]
I think this method was added to write `operatingSystem` into Active Directory when joining a machine.

**Review by michael-o — CHANGES_REQUESTED** [review]
You forgot to remove `#include <sys/utsname.h>`.

**Comment by oflebbe** [comment]
@michael-o  Thanks for the hint

**Review by michael-o — CHANGES_REQUESTED** [review]
LGTM, please squash and merge.

**Comment by oflebbe** [comment]
Hi @michael-o . Squash and merge can be done with github. No need to ask for a change.

Bildschirmfoto 2021-02-13 um 20 02 49

**Comment by michael-o** [comment]
Then go ahead, please.

**Pull request merged**
