### PR TITLE
workaround for initialization if struct addrinfo

### PR DESCRIPTION
**Pull request by oflebbe**
Workaround for issue #161 
@michael-o , could you please test?

### CODE REVIEW

**Comment by michael-o** [comment]
Testing...

**Comment by michael-o** [comment]
Intersting, the element order on macOS is like on GNU/Linux, but on HP-UX like on FreeBSD.

**Comment by oflebbe** [comment]
Why did you change the PR ?

**Review by michael-o — APPROVED** [review]
I have added another commit which documents the issue better in code and commit message. Please squash and apply the new commit message.

This works now for me on FreeBSD with Clang 10 and on HP-UX with aCC 6.29.

**Comment by michael-o** [comment]
> 
> 
> Why did you change the PR ?

I have added another commit which documents the issue better in code and commit message.

**Comment by oflebbe** [comment]
In your commit you removed the motivation to do this rather unconventional initialization. May I revert it ?

**Comment by michael-o** [comment]
Feel free to do so, but mention somewhere:
> The order or the struct members are not portable therefore do not use struct initialization, but set to default and override members explicitly.

Because this is not limited to GNU/Linux and FreeBSD, but generally all POSIX-like OS.

**Comment by oflebbe** [comment]
No strong feelings, it is not portable, right. I wanted the comment in the code rather the commit.

**Review by michael-o — APPROVED** [review]

**Pull request merged**
